name: TestCase

on:
 push:
jobs:
  TestCase:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
         
     - uses: actions/upload-artifact@v3
       with:
        name: my-artifact-allure
        path: |
          /C:\Users\7000032878\Downloads\allure-repot
          /C:\Users\7000032878\Downloads\allure-results
  
