name: Artifcate_upload
on: push 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: 'Upload Artifact'
      uses: actions/download-artifact@v3
      with:
       name: my-artifact1
       path: sreesar/project/artifact/txt.html
       retention-days: 5
    
        
