name: Artifcate_upload
on: push 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
       name: my-artifact
       path: my_file.txt
       retention-days: 5
    - name: 'Download Artifact'
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: ./project/artifact
