name:
 on:
  push:
   branches: none
  pull_request:
   branches: none
  workflow_dispatch:
 jobs:
   build-container:
    runs-on: ubuntu-lastest
    steps:
     -uses: actions/checkout@v3
     -name: Build the Docker image
    working-repository: project
     run: dockerbuild . --file Dockerfile 
