name: docker build image
 on:
  workflow_dispatch: {}

  push:
   branches: none
  pull_request:
   branches: none
  workflow_dispatch:
 jobs:
   build-container:
    runs-on: ubuntu-lastest
    steps:
     uses: actions/checkout@v3
     
     name: build docker image
     env:
          REGISTRY: ghcr.io
          OWNER: ${{ github.actor }}
          REPOSITORY: project
          IMAGE_NAME: sampleimage
         run:  
            docker build -t ${{env.REGISTRY}}/${{env.REPOSITORY}}/${{env.IMAGE_NAME}}:1 . 
