name: push folder
on:
  push:
  
jobs:
 push_repo:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
       with:
        ref: ${{ github.head_ref }}
     - run:  touch actions 
     - name: push backgenerated report
       if: success() 
       run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "add generated report"
          git push 
