name: push folder
on:
  push:
  
jobs:
 push_repo:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
       with:
        ref: ${{ github.head_ref }}
     - run:  mkdir -p test_files && cd test_files && touch actions 
     
     - name: Pushes test folder
       uses: datalbry/copy_folder_to_another_repo_action@1.0.0
       env:
        API_TOKEN_GITHUB: ${{ secrets.ACTIONS_KEY }}
       with:
        source_folder: 'test_files'
        destination_repo: 'nina878/project'
        destination_branch: 'main'
        
        
        user_email: 'nina.natarajan@sony.com'
        user_name: 'nina878'
        commit_msg: 'push the test files.'
