name: push folder
on:
  push:
  
jobs:
 push_repo:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
       with:
        ref: ${{ github.head_ref }}
     - run:  touch actions 
     
     - name: Pushes test folder
       uses: datalbry/copy_folder_to_another_repo_action@1.0.0
       env:
        API_TOKEN_GITHUB: ${{ secrets.ACTIONS_KEY }}
       with:
        source_folder: 'test_files'
        destination_repo: 'dmnemec/release-test'
        destination_folder: 'test-dir'
        user_email: 'devin.nemec@gmail.com'
        user_name: 'dmnemec'
        commit_msg: '[GHA] Update the test files.'
   #  - name: push backgenerated report
  #     if: success() 
   #    run: |
   #       git config user.name github-actions
    #      git config user.email github-actions@github.com
   #       git add .
   #       git commit -m "add generated report"
    #      git push 
