name: TestCase

on:
 push:
jobs:
  TestCase:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
        
     - uses: actions/upload-artifact@v3
       with:
        name: my-artifact-allure
        path: |
         /home/ubunu/vrt/ss-gcs-mp-webfe/allure-report
         /home/ubunu/vrt/ss-gcs-mp-webfe/allure-results
    
  
